# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-FromSledge
version:      0.01
version_from: lib/Class/DBI/FromSledge.pm
installdirs:  site
requires:
    Class::DBI::Plugin:            0.03
    Test::Exception:               0.21
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
